[package]
name = "lruk"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.8.0"
dashmap = "6.1.0"
failure = "0.1.8"
parking_lot = "0.12"
tokio = { version = "1.41.1", features = ["full"] }

[dev-dependencies]
tempfile = "3"
